"""Initial create calllog table

Revision ID: e0fee0214f72
Revises: 
Create Date: 2025-08-07 12:41:31.820259

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e0fee0214f72"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "calllog",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("call_id", sa.String(), nullable=False),
        sa.Column("agent_id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("language", sa.String(), nullable=False),
        sa.Column("call_time", sa.DateTime(), nullable=False),
        sa.Column("duration", sa.Integer(), nullable=False),
        sa.Column("transcript", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("agent_talk_ratio", sa.Float(), nullable=False),
        sa.Column("customer_sentiment_score", sa.Float(), nullable=False),
        sa.Column("embedding", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("calllog")
    # ### end Alembic commands ###
